### ISSUE TITLE
ubuntu2204使用docker启动没有输出任何log

### ISSUE THREAD

**Issue by haswelliris** [darkyzhou/seele#12]
# 测试环境
KVM 虚拟机内全新安装的 `ubuntu22.04.04`，内核版本`5.15.0-97-generic`， docker版本`Docker version 25.0.3, build 4debf41`  
按照[教程](https://seele.darkyzhou.net/getting-started)启动：
config.coml
```
[worker.action.run_container]
userns_user = "seele"
userns_uid = 1000
userns_gid = 1000
```
docker启动命令
```
docker run \
  --security-opt seccomp=unconfined \
  --security-opt apparmor=unconfined \
  --security-opt systempaths=unconfined \
  -v /etc/subuid:/etc/subuid \
  -v /etc/subgid:/etc/subgid \
  -v /sys/fs/cgroup:/sys/fs/cgroup \
  -v `pwd`:/etc/seele \
  --tmpfs /tmp:exec,mode=777,size=1G \
  --cgroupns host \
  --net host \
  ghcr.io/darkyzhou/seele
```
启动后拉取镜像，然后口没有任何输出了  
但用 **curl往绑定端口提交评测任务，可以返回正确执行代码后的结果**，但是在docker logs里仍然没有任何信息
# 问题
请问这种情况有啥排查思路吗？
已经用`docker exec -it xxx /bin/bash`进入容器查看，
有`/tini -- /usr/local/bin/seele`进程和其他N=cpu+1个`/usr/local/bin/seele`进程/线程

**Comment by haswelliris** [comment]
换了一种启动方式，创建容器然后手动执行seele config.toml
启动命令(跟教程一样，只是新增了 `-it` 和 `/bin/bash`：
```
docker run -it   --security-opt seccomp=unconfined   --security-opt apparmor=unconfined   --security-opt systempaths=unconfined   -v /etc/subuid:/etc/subuid   -v /etc/subgid:/etc/subgid   -v /sys/f
s/cgroup:/sys/fs/cgroup   -v `pwd`:/etc/seele   --tmpfs /tmp:exec,mode=777,size=2G   --cgroupns host   --net host   ghcr.io/darkyzhou/seele /bin/bash
```
进入`/etc/seele`，执行`seele config.toml` 输出：

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error initializing cgroup subtrees
> 
> Caused by:
>     0: failed to write +cpu +cpuset +memory +io +pids to "/sys/fs/cgroup/system.slice/docker-fe822b95f20efe045cd9f532fcde1185e35a11b306daf3a68100088e694e682a.scope/cgroup.subtree_control"
>     1: Device or resource busy (os error 16)', src/main.rs:254:10
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  
然而检查`/sys/fs/cgroup/user.slice/user-1000.slice/cgroup.controllers`，是有`cpuset cpu io memory pids`的

**Comment by darkyzhou** [comment]
1. 正如[文档](https://seele.darkyzhou.net/configurations/file)里所说的，默认的日志等级 `log_level` 是 `warn`，如果你像看到更多日志输出可以尝试改成 `info` 或更低的等级。我这边也在文档里提示一下吧。
2. 这种启动方式会因为 cgroup 的设计限制失败，`Device or resource busy` 的意思是当前 cgroup 已经包含进程（也即你的 `/bin/bash`），不能被 Seele 修改。
